### ISSUE TITLE
firo-client wallet

### ISSUE THREAD

**Issue by SaeeD2002DeeaS** [LedgerHQ/wallet-api#109]
Good day to all,
I have issue for my wallet I lose passphrase and seed phrase, however I want recovered passphrase to lock wallet.
I heard and watch multi video how to recovered passwords but I tried from (wallet.dat) by hashcat but I don't get any result
so any one have a way to recovered passphrase.
Thanks

**Comment by adrienlacombe-ledger** [comment]
Still not the right place, please stop the spam.

**Comment by SaeeD2002DeeaS** [comment]
where the place can wort my issue

**Comment by adrienlacombe-ledger** [comment]
I don't know
