### ISSUE TITLE
Change `device.transport` params

### ISSUE THREAD

**Issue by Justkant** [LedgerHQ/wallet-api#163]
Only take `deviceId` as param and could probably be optional too

**Comment by adrienlacombe-ledger** [comment]
@Justkant what do we do with this? ty

**Comment by Justkant** [comment]
This one will not actually change as I don't want to do a breaking change but we need to split the current implementation of `device.transport` so we can open a transport without showing the device selection screen for recover.
I should be able to create a PR today for the changes

**Comment by adrienlacombe-ledger** [comment]
ty Ser
