### ISSUE TITLE
Export issue (Module not found: Error: Can't resolve '@ledgerhq/wallet-api-client')

### ISSUE THREAD

**Issue by AlexBardadym** [LedgerHQ/wallet-api#204]
I try to implement wallet-api into my React application and going through the example
https://wallet.api.live.ledger.com/react/configuration

But I got this error - Module not found: Error: Can't resolve '@ledgerhq/wallet-api-client'

I tried to downgrade to the previous version of 'wallet-api-client' ("@ledgerhq/wallet-api-client": "^0.15.5") to check the path of imported Transport and WindowMessageTransport and I found that 'Transport' exported from - @ledgerhq/wallet-api-client/node_modules/@ledgerhq/wallet-api-core/lib/transports/types.d.ts
And the 'WindowMessageTransport' from -
@ledgerhq/wallet-api-client/node_modules/@ledgerhq/wallet-api-core/lib/transports/WindowMessageTransport.d.ts

But in version 1.0.0 path is different and even if I put the entire way to the 'Transport' and 'WindowMessageTransport' (like '@ledgerhq/wallet-api-client/lib/core/src/transports/WindowMessageTransport') still got an import error.

The same issue for the 'WalletAPIProvider' from 'wallet-api-client-react'.

Could you please check the exports.

Thanks

**Comment by bill0x2A** [comment]
Reproducing this as well, importing anything from the `@ledgerhq/wallet-api-client` package results in:

```js
import { WalletAPIClient } from '@ledgerhq/wallet-api-client';
```

```
Unable to resolve path to module '@ledgerhq/wallet-api-client'
```

packages/frontend/package.json:

```json
"dependencies": {
   ...
    "@ledgerhq/wallet-api-client": "1.0.0",
    "@ledgerhq/wallet-api-core": "1.0.0",
   ...
}
```

I am using a Lerna monorepo, with the `/node_modules/@ledgerhq` folder located at the root of the project. I do not think this is relevant though as `nohoisting` the packages has no effect on this error.

**Comment by bill0x2A** [comment]
Cloned the repo to try and figure out what is going on.

It looks like the build process is not actually generating index files where they are expected.

Running `pnpm build` in `packages/client` produces:

```
client/
├─ lib/
│  ├─ client/src
│  │   ├─ index.js
│  │   ├─ ...
│  ├─ core/src
│  │   ├─ index.js
│  │   ├─ ...
├─ lib-es/
│  ├─ client/src
│  │   ├─ index.js
│  │   ├─ ...
│  ├─ core/src
│  │   ├─ index.js
│  │   ├─ ...
```

With no `index.js` at the root level of `/lib` or `lib-es`. Could be something to do with how turbopack handles build / exports?

Either way the `package.json` expects a main file at these root levels:

**packages/client/package.json**
```json
"main": "lib/index.js",
  "module": "lib-es/index.js",
  "types": "lib/index.d.ts",
  "files": [
    "/lib",
    "/lib-es"
  ],
```

I have temporarily and manually fixed this in my project by adding these root level `index.js` files:

**/node_modules/@ledgerhq/wallet-api-client/lib-es/index.js**
```js
export * from './client/src';
```

**/node_modules/@ledgerhq/wallet-api-client/lib/index.js**
```js
"use strict";
/* istanbul ignore file */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./client/src"), exports);
//# sourceMappingURL=index.js.map

```

My build will then work as expected.

**Conclusion**
Something in the build process is causing these index files to be generated in an unexpected location, meaning it is not possible to import from the client package.

I'm attempting to find a fix in the build process currently, and will open a PR if I can find a solution, however I am not _too_ experienced with Turbopack so I may not be able to find a fix in a reasonable amount of time.

**Comment by AlexBardadym** [comment]
> 

Unfortunately, this only solves the problems of errors in the code editor, but at the stage of building the React application, import errors still appear.

Also, fixes locally will not solve the problem at the deployment stage, because. we have СI/СD configured and the assembly before the deployment takes place on the server side.

But thanks for the advice!

**Comment by bill0x2A** [comment]
Indeed, unfortunately. Facing the same issues.

Still looking into making a PR to propose a fix, but hopefully this can help your local development process in the meantime.

I'm currently importing the patched module from my local files as a holdover.

**Comment by AlexBardadym** [comment]
@bill0x2A I also tried the downgrade version but the needed functionality does not exist in the previous version for my App.

Thanks!

Let's wait for the approve of your PR.

**Comment by ArttuPakarinen** [comment]
I get the same error with example provided in here:
https://wallet.api.live.ledger.com/core/configuration

Code:

```
import { WalletAPIClient, WindowMessageTransport } from "@ledgerhq/wallet-api-client";
 
async function initializeWalletApiClient() {
  // Step 1: Initialize and connect the Window Message Transport
  const windowMessageTransport = new WindowMessageTransport();
  windowMessageTransport.connect();
 
  // Step 2: Initialize Wallet API Client with the Window Message Transport
  const walletApiClient = new WalletAPIClient(windowMessageTransport);
 
  // The Wallet API client is now initialized, and you can use it to interact with Wallet API.
  // For example, accessing accounts:
  // const accounts = await walletApiClient.account.getAccounts();
 
  // Your application logic here...
 
  // Step 3: Disconnect when done to ensure the communication is properly closed
  windowMessageTransport.disconnect();
}
 
// Execute the function
initializeWalletApiClient().catch((error) => console.error(error));
```


The error:
```

node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/.../node_modules/@ledgerhq/wallet-api-client/' imported from /.../index.js
    at new NodeError (node:internal/errors:400:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:235:9)
    at packageResolve (node:internal/modules/esm/resolve:876:14)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

**Comment by ComradeAERGO** [comment]
We are looking into this issue with the way 1.0.0 version were bundled.

In the meantime, you can downgrade to 
- [@ledgerhq/wallet-api-client@0.15.5](https://github.com/LedgerHQ/wallet-api/releases/tag/%40ledgerhq%2Fwallet-api-client%400.15.5)
- [@ledgerhq/wallet-api-client-react@0.2.1](https://github.com/LedgerHQ/wallet-api/releases/tag/%40ledgerhq%2Fwallet-api-client-react%400.2.1)

Those packages are equal to v1.0.0 in terms of features,
v1.0.0 was just a bump of version for the public release.
