### ISSUE TITLE
Debounce / fix "event.account.updated"

### ISSUE THREAD

**Issue by chabroA** [LedgerHQ/wallet-api#62]
Due to Ledger Live frequent synchronisation, live apps are spammed by `event.account.updated` events.
Even though the accounts are not actually updated per say. Only the reference of the account object is actually updated on LL side even when their values might not have changed.

**Comment by Justkant** [comment]
This has been fixed here: https://github.com/LedgerHQ/ledger-live/pull/1901/commits/6f004ef8d71dd064766e43818ea14d91be806f59
