### ISSUE TITLE
wallet-api-server sets unhandled cryptocurrencies, accounts and permissions

### ISSUE THREAD

**Issue by chabroA** [LedgerHQ/wallet-api#81]
The `setPermissions`, `setCurrencies` and `setAccounts` methods of the the server (cf. [here](https://github.com/LedgerHQ/wallet-api/blob/main/packages/server/src/WalletAPIServer.ts#L49-L63)) don't check the arguments they receive and blindly setup the server internal state with those.

This can lead to unexpected behaviour and errors if a wallet implementation pass a list of crypto that is not handled by the wallet-api (cf. details bellow for example).
Same thing for accounts and permissions.

<details>
<summary> 📸  💥  </summary>

![Screenshot 2022-12-22 at 12 23 58](https://user-images.githubusercontent.com/9203826/209153376-3580cd9f-9688-4612-b7f6-6abfafcb5ed1.png)

</details>

In this specific example, Ledger Live should also be fixed (cf. [this function](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/wallet-api/helpers.ts#L10-L14)) since the wallet sets currencies that are not handled by the wallet-api (and/or the wallet-api should silently discard invalid currencies if we want to avoid a runtime crash since this list could be updated at runtime)

**Comment by adrienlacombe-ledger** [comment]
not stale
